mythicMobsSupport: false

clearProtectionOnLeave: false
# Default: false
# Should the drop protection be cleared when items owner(the one who made them drop) leaves the server.

clearProtectionOnDeath: false
# Default: false
# Should the drop protection be cleared on death of items' owner(the one who made them drop).

preventFromHoppers: true
# Default: true
# Should the protected items prevented from going into hoppers.

mobsCanPickUp: false
# Default: false
# Should mobs pick up protected items.

timeToProtect: 10
# Default: 10
# Time to protect dropped loot(in seconds).
# Set this value to 0 or negative if you want protection to be endless.
# Decimals will just get rounded.

illegalArgumentsMessage: '&1&l[&e&lRPGDrop&1&l] &6&l>>> &f&lIllegal arguments.'

configReloadMessage: '&1&l[&e&lRPGDrop&1&l] &6&l>>> &f&lConfig reloaded.'

clearProtectionMessage: '&1&l[&e&lRPGDrop&1&l] &6&l>>> &f&lCleared protection from all items on server.'