name: RPGDrop
version: 1.0.6
main: me.ruskaz.rpgdrop.Main
api-version: 1.16
softdepend: [ MythicMobs ]
authors: [ RuSKaz ]
description: Allows you to protect people's drop!
permissions:
  rpgdrop.protection:
    default: op
    description: People with this permission will have their drops protected.
  rpgdrop.commands:
    default: op
    description: People with this permission will have access to /rpgdrop command.

commands:
  rpgdrop:
    permission: rpgdrop.commands
    description: Command is made either to clear protection from all items in all worlds or to reload config.
    usage: /rpgdrop clear/reload
